[package]
name = "assume-role"
version = "0.1.0"
authors = ["Adam Batkin <adam@batkin.net>"]
edition = "2018"

[dependencies]
anyhow = "1"
structopt = "0.3.7"
directories = "2.0.2"
rusoto_core = { version = "0.42.0", features = ["rustls"], default-features = false }
rusoto_sts = { version = "0.42.0", features = ["rustls"], default-features = false }
rust-ini = { version = "0.14.0", features = ["preserve_order"] }
